#!/usr/bin/env bash

envr=~/Projects/env

mkdir -vp ~/.bin ~/Projects

echo 'export PATH="~/.bin:$PATH"' > ~/.bashrc

# nvim install
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
mv nvim.appimage ~/.bin/nvim

# nvim packer install
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# dotfiles
git clone https://github.com/turtlebasket/env $envr
mkdir -p ~/.config/nvim
cp -v $envr/config/neovim/macos/init.lua ~/.config/nvim/init.lua

