# ~/.tmux.conf

set -g monitor-bell on

# Ctrl+a instead of Ctrl+b for command prefix (like Screen)
# set -g prefix C-a
# unbind C-b
# bind C-a send-prefix

# ctrl+b C creates a new window to the right (NOTE: capital C)
# NOTE: this doesn't work for some reason!!
# unbind -T prefix C
# bind   -T prefix C new-window -a .

unbind l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

